# Friendlier error messages for students. Do not edit this file.

import pytest

HINTS = [
    ["takes no arguments",
     "Your class has no __init__ method yet, or it is spelled wrong.\n"
     "It must be:  def __init__(self, ...):   (two underscores on each side)"],

    ["positional argument but",
     "One of your methods is missing 'self'.\n"
     "Every method must start with self, for example:  def pay(self, fare):"],

    ["'NoneType' object has no attribute",
     "Something returned None (nothing) when an object was expected.\n"
     "Check that your method has a 'return' statement."],

    ["object has no attribute",
     "An attribute or method is missing, or its name is spelled differently\n"
     "from the README. Names must match EXACTLY, including capital letters.\n"
     "Attributes must be created inside __init__ with  self.name = ..."],

    ["unsupported operand type(s)",
     "You are doing maths with None. A method probably forgot to 'return'\n"
     "its answer, or an attribute was never set in __init__."],
]


@pytest.hookimpl(hookwrapper=True)
def pytest_runtest_makereport(item, call):
    outcome = yield
    report = outcome.get_result()
    if report.when != "call" or not report.failed or call.excinfo is None:
        return
    message = str(call.excinfo.value)
    for hint in HINTS:
        if hint[0] in message:
            report.sections.append(["HINT", hint[1]])
            return


def pytest_assertrepr_compare(op, left, right):
    if op == "==" and left is None:
        return [
            "Your method returned None (nothing).",
            "",
            "This almost always means one of two things:",
            "  1. You left 'pass' in the method instead of writing code.",
            "  2. You wrote the code but forgot the 'return' statement.",
            "",
            "The test expected: " + repr(right),
        ]
